### ISSUE TITLE
download link is misleading

### ISSUE THREAD

**Issue by danielskatz** [Parsl/parsl-old-web#1]
on https://parsl.github.io, we now have a button at the bottom for install parsl

This should probably not do to the source where it goes now, but instead, should point to https://parsl.readthedocs.io/en/latest/quick/quickstart.html#installing

**Comment by danielskatz** [comment]
I think this should be assigned to @kylechard but I don't have permission to make an assignment

**Comment by kylechard** [comment]
Done.
